/**:
  ros__parameters:
    cmd_freq: 100.0  # Hz of platform commands send
    info_freq: 10.0  # Hz of platform info publish
    external_odom: false  # Flag to use external odometry source
    device: "/dev/ttyACM0"  # Serial port to connect to the Platform
    baudrate: 115200 # Baudrate of the serial port
    thrust:
      max : 15.0  # Max thrust to send to platform (N)
      min : 0.15  # Min thrust to send to platform (N)
    roll_rate:
      max : 711.0 # Max roll rate to send to platform (deg/s) # ATTENTION: this is in deg/s
      min : -711.0 # Min roll rate to send to platform (deg/s) # ATTENTION: this is in deg/s
    pitch_rate:
      max : 711.0  # Max pitch rate to send to platform (deg/s) # ATTENTION: this is in deg/s
      min : -711.0  # Min pitch rate to send to platform (deg/s) # ATTENTION: this is in deg/s
    yaw_rate:
      max : 711.0  # Max yaw rate to send to platform (deg/s) # ATTENTION: this is in deg/s
      min : -711.0  # Min yaw rate to send to platform (deg/s) # ATTENTION: this is in deg/s
    thrust_map:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0

